module.exports = {
  User: require('./User'),
  MentorProfile: require('./MentorProfile'),
  MentorRequest: require('./MentorRequest'),
  Project: require('./Project'),
  ProjectMember: require('./ProjectMember'),
  Task: require('./Task'),
  TaskComment: require('./TaskComment'),
  ActivityLog: require('./ActivityLog'),
  Meeting: require('./Meeting'),
  MeetingAttendance: require('./MeetingAttendance'),
  Announcement: require('./Announcement'),
  DiaryEntry: require('./DiaryEntry'),
  InternalEvaluation: require('./InternalEvaluation'),
  PresentationEvent: require('./PresentationEvent'),
  PresentationSlot: require('./PresentationSlot'),
  PresentationEvaluation: require('./PresentationEvaluation'),
  RefreshToken: require('./RefreshToken'),
  FreezeSettings: require('./FreezeSettings'),
};
